# Generated by Django 5.2.6 on 2025-09-08 09:53

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="documents",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=api.models.Company._documents_upload_path,
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="sertificate",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=api.models.Company._certificate_upload_path,
            ),
        ),
    ]
