# Generated by Django 5.2.6 on 2025-09-08 10:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_alter_company_documents_alter_company_sertificate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="users/images/"),
        ),
    ]
