# Generated by Django 4.2.7 on 2025-09-10 04:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_company_logo_subcategory_item_subcategory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("profile_updated", "profile_updated"),
                    ("password_changed", "password_changed"),
                    ("company_profile_updated", "company_profile_updated"),
                    ("certificate_added", "certificate_added"),
                    ("certificate_removed", "certificate_removed"),
                    ("member_added", "member_added"),
                    ("member_removed", "member_removed"),
                    ("item_created", "item_created"),
                    ("item_updated", "item_updated"),
                    ("item_deleted", "item_deleted"),
                ],
                max_length=50,
            ),
        ),
    ]
