# Generated by Django 4.2.7 on 2025-09-10 05:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_alter_notification_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="sms_code",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="sms_code_expires",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
