# Generated by Django 4.2.7 on 2025-09-10 05:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_user_sms_code_user_sms_code_expires"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="sms_code",
        ),
        migrations.RemoveField(
            model_name="user",
            name="sms_code_expires",
        ),
    ]
