# Generated by Django 4.2.7 on 2025-09-10 06:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0010_alter_notification_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemDeletionReason",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("company_name", models.CharField(max_length=200)),
                ("company_id", models.UUIDField()),
                ("user_name", models.CharField(max_length=100)),
                ("user_phone", models.CharField(max_length=20)),
                ("user_id", models.UUIDField()),
                ("subject", models.TextField(help_text="Mahsulotni o'chirish sababi")),
                ("deleted_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-deleted_at"],
            },
        ),
    ]
