# Generated by Django 4.2.7 on 2025-09-10 07:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0011_itemdeletionreason"),
    ]

    operations = [
        migrations.AddField(
            model_name="subcategory",
            name="unit",
            field=models.CharField(
                choices=[
                    ("tonna", "tonna"),
                    ("m3", "m3"),
                    ("dona", "dona"),
                    ("kg", "kg"),
                    ("qop", "qop"),
                    ("quti", "quti"),
                    ("m", "m"),
                ],
                default="tonna",
                max_length=50,
            ),
        ),
    ]
