# Generated by Django 4.2.7 on 2025-09-10 07:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0012_subcategory_unit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subcategory",
            name="unit",
            field=models.CharField(
                blank=True,
                choices=[
                    ("tonna", "tonna"),
                    ("m3", "m3"),
                    ("dona", "dona"),
                    ("kg", "kg"),
                    ("qop", "qop"),
                    ("quti", "quti"),
                    ("m", "m"),
                ],
                help_text="Sub kategoriya uchun default birlik",
                max_length=20,
                null=True,
            ),
        ),
    ]
