# Generated by Django 4.2.7 on 2025-09-10 07:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0013_alter_subcategory_unit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="unit",
            field=models.CharField(
                choices=[
                    ("tonna", "tonna"),
                    ("m3", "m3"),
                    ("dona", "dona"),
                    ("kg", "kg"),
                    ("qop", "qop"),
                    ("quti", "quti"),
                    ("m", "m"),
                ],
                default="tonna",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="request",
            name="unit",
            field=models.CharField(
                choices=[
                    ("tonna", "tonna"),
                    ("m3", "m3"),
                    ("dona", "dona"),
                    ("kg", "kg"),
                    ("qop", "qop"),
                    ("quti", "quti"),
                    ("m", "m"),
                ],
                max_length=50,
            ),
        ),
    ]
