# Generated by Django 4.2.7 on 2025-09-11 09:36

import api.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0014_alter_item_unit_alter_request_unit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("profile_updated", "profile_updated"),
                    ("password_changed", "password_changed"),
                    ("company_profile_updated", "company_profile_updated"),
                    ("certificate_added", "certificate_added"),
                    ("certificate_removed", "certificate_removed"),
                    ("member_added", "member_added"),
                    ("member_removed", "member_removed"),
                    ("item_created", "item_created"),
                    ("item_updated", "item_updated"),
                    ("item_deleted", "item_deleted"),
                    ("new_request", "new_request"),
                    ("new_offer", "new_offer"),
                    ("offer_accepted", "offer_accepted"),
                    ("offer_rejected", "offer_rejected"),
                    ("order_created", "order_created"),
                    ("order_updated", "order_updated"),
                    ("order_completed", "order_completed"),
                    ("rating_request", "rating_request"),
                    ("info", "info"),
                ],
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="Offer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("price", models.BigIntegerField()),
                ("currency", models.CharField(default="UZS", max_length=3)),
                ("eta_days", models.IntegerField()),
                ("delivery_included", models.BooleanField(default=False)),
                ("payment_terms", models.TextField(blank=True, null=True)),
                ("comment", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("kutilmoqda", "kutilmoqda"),
                            ("qabul_qilindi", "qabul_qilindi"),
                            ("rad_etildi", "rad_etildi"),
                            ("muddati_tugadi", "muddati_tugadi"),
                        ],
                        default="kutilmoqda",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expires_at",
                    models.DateTimeField(default=api.models.default_offer_expires_at),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offers",
                        to="api.request",
                    ),
                ),
                (
                    "supplier_company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offers",
                        to="api.company",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="order",
            name="offer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="api.offer",
            ),
        ),
        migrations.AddIndex(
            model_name="offer",
            index=models.Index(fields=["request", "status"], name="idx_off_req_stat"),
        ),
    ]
