# Generated by Django 4.2.7 on 2025-09-12 06:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0015_alter_notification_type_offer_order_offer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("ochilgan", "ochilgan"),
                    ("bajarilmoqda", "bajarilmoqda"),
                    ("bajarildi", "bajarildi"),
                    ("bekor_qilindi", "bekor_qilindi"),
                ],
                default="ochilgan",
                max_length=50,
            ),
        ),
    ]
