# Generated by Django 4.2.7 on 2025-09-12 06:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0016_alter_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="offer",
            name="rejection_reason",
            field=models.TextField(blank=True, null=True),
        ),
    ]
