# Generated by Django 4.2.7 on 2025-09-12 06:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0017_offer_rejection_reason"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offer",
            name="status",
            field=models.CharField(
                choices=[
                    ("kutilmoqda", "kutilmoqda"),
                    ("qabul_qilindi", "qabul_qilindi"),
                    ("rad_etildi", "rad_etildi"),
                    ("bekor_qilindi", "bekor_qilindi"),
                    ("muddati_tugadi", "muddati_tugadi"),
                ],
                default="kutilmoqda",
                max_length=50,
            ),
        ),
    ]
