# Generated by Django 4.2.7 on 2025-09-12 06:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0018_alter_offer_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="request",
            name="status",
            field=models.CharField(
                choices=[
                    ("ochiq", "ochiq"),
                    ("yopilgan", "yopilgan"),
                    ("bekor_qilindi", "bekor_qilindi"),
                    ("muddati_tugadi", "muddati_tugadi"),
                ],
                default="ochiq",
                max_length=50,
            ),
        ),
    ]
