# Generated by Django 4.2.7 on 2025-09-12 07:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0019_alter_request_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="request",
            name="cancellation_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="request",
            name="status",
            field=models.CharField(
                choices=[
                    ("ochiq", "ochiq"),
                    ("yopilgan", "yopilgan"),
                    ("muddati_tugadi", "muddati_tugadi"),
                ],
                default="ochiq",
                max_length=50,
            ),
        ),
    ]
