# Generated by Django 4.2.7 on 2025-09-12 12:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0021_alter_request_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivery_photos",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_confirmed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_document",
            field=models.FileField(blank=True, null=True, upload_to="orders/payments/"),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_terms",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="ttn_document",
            field=models.FileField(blank=True, null=True, upload_to="orders/ttn/"),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("ochilgan", "ochilgan"),
                    ("to_lov_kutilmoqda", "to'lov kutilmoqda"),
                    ("to_lov_qilindi", "to'lov qilindi"),
                    ("yeg_ilmoqda", "yeg'ilmoqda"),
                    ("yo_lda", "yo'lda"),
                    ("yetib_bordi", "yetib bordi"),
                    ("yakunlandi", "yakunlandi"),
                    ("bekor_qilindi", "bekor qilindi"),
                ],
                default="ochilgan",
                max_length=50,
            ),
        ),
    ]
