# Generated by Django 4.2.7 on 2025-09-13 05:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0022_order_delivery_photos_order_payment_confirmed_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="offer",
            name="contact_person",
            field=models.CharField(
                blank=True, help_text="Mas'ul shaxs", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="offer",
            name="contact_phone",
            field=models.CharField(
                blank=True, help_text="Aloqa telefoni", max_length=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="offer",
            name="max_order_quantity",
            field=models.IntegerField(
                blank=True, help_text="Maksimal buyurtma miqdori", null=True
            ),
        ),
        migrations.AddField(
            model_name="offer",
            name="min_order_quantity",
            field=models.IntegerField(default=1, help_text="Minimal buyurtma miqdori"),
        ),
        migrations.AddField(
            model_name="offer",
            name="production_capacity",
            field=models.IntegerField(
                blank=True, help_text="Ishlab chiqarish quvvati (kuniga)", null=True
            ),
        ),
        migrations.AddField(
            model_name="offer",
            name="quality_certificates",
            field=models.JSONField(
                blank=True, default=list, help_text="Sifat sertifikatlari"
            ),
        ),
        migrations.AddField(
            model_name="offer",
            name="special_conditions",
            field=models.TextField(blank=True, help_text="Maxsus shartlar", null=True),
        ),
        migrations.AddField(
            model_name="offer",
            name="warranty_period",
            field=models.IntegerField(default=0, help_text="Kafolat muddati (oy)"),
        ),
    ]
