# Generated by Django 4.2.7 on 2025-09-13 05:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0023_offer_contact_person_offer_contact_phone_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="offer",
            name="contact_person",
        ),
        migrations.RemoveField(
            model_name="offer",
            name="contact_phone",
        ),
        migrations.RemoveField(
            model_name="offer",
            name="max_order_quantity",
        ),
        migrations.RemoveField(
            model_name="offer",
            name="min_order_quantity",
        ),
        migrations.RemoveField(
            model_name="offer",
            name="production_capacity",
        ),
        migrations.RemoveField(
            model_name="offer",
            name="quality_certificates",
        ),
    ]
