# Generated by Django 4.2.7 on 2025-09-13 05:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0024_remove_offer_contact_person_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="offer",
            name="payment_terms",
        ),
    ]
