# Generated by Django 4.2.7 on 2025-09-13 09:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0025_remove_offer_payment_terms"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("ochilgan", "ochilgan"),
                    ("to_lov_kutilmoqda", "to'lov kutilmoqda"),
                    ("to_lov_qilindi", "to'lov qilindi"),
                    ("yeg_ilmoqda", "yeg'ilmoqda"),
                    ("yo_lda", "yo'lda"),
                    ("yetib_bordi", "yetib bordi"),
                    ("naqd_tolov_qabul_qilindi", "naqd to'lov qabul qilindi"),
                    ("yakunlandi", "yakunlandi"),
                    ("bekor_qilindi", "bekor qilindi"),
                ],
                default="ochilgan",
                max_length=50,
            ),
        ),
    ]
