# Generated by Django 4.2.7 on 2025-09-13 10:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0027_alter_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="request",
            name="budget_from",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="request",
            name="budget_to",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
