# Generated by Django 4.2.7 on 2025-09-13 10:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0028_alter_request_budget_from_alter_request_budget_to"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("profile_updated", "profile_updated"),
                    ("password_changed", "password_changed"),
                    ("company_profile_updated", "company_profile_updated"),
                    ("certificate_added", "certificate_added"),
                    ("certificate_removed", "certificate_removed"),
                    ("member_added", "member_added"),
                    ("member_removed", "member_removed"),
                    ("item_created", "item_created"),
                    ("item_updated", "item_updated"),
                    ("item_deleted", "item_deleted"),
                    ("new_request", "new_request"),
                    ("new_offer", "new_offer"),
                    ("offer_accepted", "offer_accepted"),
                    ("offer_rejected", "offer_rejected"),
                    ("order_created", "order_created"),
                    ("order_updated", "order_updated"),
                    ("order_completed", "order_completed"),
                    ("order_payment_confirmed", "order_payment_confirmed"),
                    ("order_production_started", "order_production_started"),
                    ("order_shipped", "order_shipped"),
                    ("order_delivered", "order_delivered"),
                    ("order_cancelled", "order_cancelled"),
                    ("rating_request", "rating_request"),
                    ("rating_received", "rating_received"),
                    ("info", "info"),
                ],
                max_length=50,
            ),
        ),
    ]
