# Generated by Django 4.2.7 on 2025-09-17 08:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0029_alter_notification_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="zavod",
            field=models.CharField(
                blank=True,
                help_text="Ishlab chiqaruvchi zavod",
                max_length=200,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="Razmer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="razmer",
                        to="api.category",
                    ),
                ),
                (
                    "subcategory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="razmers",
                        to="api.subcategory",
                    ),
                ),
            ],
            options={
                "unique_together": {("subcategory", "name")},
            },
        ),
        migrations.AddField(
            model_name="item",
            name="razmer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="items",
                to="api.razmer",
            ),
        ),
    ]
