# Generated by Django 4.2.7 on 2025-09-17 08:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0030_item_zavod_razmer_item_razmer"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="razmer",
            index=models.Index(
                fields=["category", "subcategory"], name="idx_razmer_cat_sub"
            ),
        ),
    ]
