# Generated by Django 5.2.6 on 2025-09-22 11:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_category_factory_unit_user_device_token_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                max_length=20,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\+998\\d{9}$",
                        message="Telefon raqami +998XXXXXXXXX formatida bo'lishi kerak",
                    )
                ],
            ),
        ),
    ]
