# Generated by Django 5.2.6 on 2025-09-29 09:00

import api.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_alter_user_username"),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("company_license", "Kompaniya litsenziyasi"),
                            ("tax_certificate", "Soliq guvohnomasi"),
                            ("bank_statement", "Bank ma'lumotnomasi"),
                            ("contract", "Shartnoma"),
                            ("invoice", "Hisob-faktura"),
                            ("ttn", "TTN (Transport hujjati)"),
                            ("receipt", "Qabul qilish hujjati"),
                            ("certificate", "Sertifikat"),
                            ("specification", "Texnik xususiyatlar"),
                            ("warranty", "Kafolat hujjati"),
                            ("didox_contract", "Didox Shartnoma"),
                            ("didox_invoice", "Didox Hisob-faktura"),
                            ("didox_statement", "Didox Ma'lumotnoma"),
                            ("other", "Boshqa hujjat"),
                        ],
                        max_length=50,
                        verbose_name="Hujjat turi",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Foydalanuvchi tomonidan berilgan nom",
                        max_length=255,
                        verbose_name="Hujjat nomi",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Hujjat haqida qo'shimcha ma'lumot",
                        verbose_name="Tavsif",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=api.models.document_upload_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "pdf",
                                    "jpg",
                                    "jpeg",
                                    "png",
                                    "doc",
                                    "docx",
                                    "xls",
                                    "xlsx",
                                ]
                            )
                        ],
                        verbose_name="Fayl",
                    ),
                ),
                (
                    "file_name",
                    models.CharField(max_length=255, verbose_name="Asl fayl nomi"),
                ),
                (
                    "file_size",
                    models.BigIntegerField(verbose_name="Fayl hajmi (bytes)"),
                ),
                (
                    "content_type",
                    models.CharField(max_length=100, verbose_name="Fayl turi"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Kutilmoqda"),
                            ("processing", "Qayta ishlanmoqda"),
                            ("verified", "Tasdiqlangan"),
                            ("rejected", "Rad etilgan"),
                            ("expired", "Muddati tugagan"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Holat",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual_upload", "Qo'lda yuklangan"),
                            ("auto_generated", "Avtomatik yaratilgan"),
                            ("didox_integration", "Didox integratsiya"),
                            ("api_import", "API orqali import"),
                        ],
                        default="manual_upload",
                        max_length=30,
                        verbose_name="Manba",
                    ),
                ),
                (
                    "didox_document_id",
                    models.CharField(
                        blank=True,
                        help_text="Didox tizimidagi hujjat identifikatori",
                        max_length=100,
                        null=True,
                        verbose_name="Didox hujjat ID",
                    ),
                ),
                (
                    "didox_metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Didox dan kelgan qo'shimcha ma'lumotlar",
                        verbose_name="Didox metadata",
                    ),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Tasdiqlash vaqti"
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(blank=True, verbose_name="Rad etish sababi"),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Amal qilish muddati"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Flexible data storage for future integrations",
                        verbose_name="Qo'shimcha ma'lumotlar",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        help_text="Kompaniya hujjatlari uchun",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="api.company",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        help_text="Buyurtma bilan bog'liq hujjatlar uchun",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="new_documents",
                        to="api.order",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_documents",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Tasdiqlagan shaxs",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hujjat",
                "verbose_name_plural": "Hujjatlar",
                "db_table": "documents",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DocumentShare",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "share_type",
                    models.CharField(
                        choices=[
                            ("view_only", "Faqat ko'rish"),
                            ("download", "Yuklab olish"),
                            ("comment", "Izoh qoldirish"),
                        ],
                        default="view_only",
                        max_length=20,
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, help_text="Ulashish muddati", null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("accessed_at", models.DateTimeField(blank=True, null=True)),
                ("access_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shares",
                        to="api.document",
                    ),
                ),
                (
                    "shared_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents_shared",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shared_with",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shared_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Hujjat ulashish",
                "verbose_name_plural": "Hujjat ulashishlar",
                "db_table": "document_shares",
            },
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["user", "document_type"], name="documents_user_id_588d9f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["order", "document_type"], name="documents_order_i_9497a6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["company", "document_type"], name="documents_company_654c10_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["status", "created_at"], name="documents_status_497c5a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["didox_document_id"], name="documents_didox_d_3bfd4d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["expires_at"], name="documents_expires_111bd4_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="documentshare",
            unique_together={("document", "shared_with")},
        ),
    ]
