# Generated by Django 5.2.6 on 2025-10-01 06:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_document_documentshare_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="contract_url",
        ),
        migrations.RemoveField(
            model_name="order",
            name="invoice_url",
        ),
        migrations.RemoveField(
            model_name="order",
            name="payment_reference",
        ),
        migrations.AddField(
            model_name="order",
            name="contract_document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contract_orders",
                to="api.document",
                verbose_name="Shartnoma hujjati",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="invoice_document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invoice_orders",
                to="api.document",
                verbose_name="Hisob-faktura hujjati",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_confirmed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="To'lov tasdiqlangan vaqt"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_confirmed_by_seller",
            field=models.BooleanField(
                default=False, verbose_name="Sotuvchi tomonidan to'lov tasdiqlangan"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_proof_document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payment_proof_orders",
                to="api.document",
                verbose_name="To'lov hujjati",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="ttn_document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ttn_orders",
                to="api.document",
                verbose_name="TTN hujjati",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "Yaratilgan"),
                    ("awaiting_payment", "To'lov kutilmoqda"),
                    ("payment_confirmed", "To'lov tasdiqlangan"),
                    ("in_preparation", "Tayyorlanmoqda"),
                    ("ready_for_delivery", "Yetkazib berishga tayyor"),
                    ("in_transit", "Yo'lda"),
                    ("delivered", "Yetkazib berilgan"),
                    ("confirmed", "Tasdiqlangan"),
                    ("completed", "Yakunlangan"),
                    ("cancelled", "Bekor qilingan"),
                ],
                default="created",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="orderdocument",
            name="uploaded_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_documents",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
