# Generated by Django 5.2.6 on 2025-10-01 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_remove_order_contract_url_remove_order_invoice_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("company_license", "Kompaniya litsenziyasi"),
                    ("tax_certificate", "Soliq guvohnomasi"),
                    ("bank_statement", "Bank ma'lumotnomasi"),
                    ("contract", "Shartnoma"),
                    ("invoice", "Hisob-faktura"),
                    ("ttn", "TTN (Transport hujjati)"),
                    ("receipt", "Qabul qilish hujjati"),
                    ("payment_proof", "To'lov hujjati"),
                    ("certificate", "Sertifikat"),
                    ("specification", "Texnik xususiyatlar"),
                    ("warranty", "Kafolat hujjati"),
                    ("didox_contract", "Didox Shartnoma"),
                    ("didox_invoice", "Didox Hisob-faktura"),
                    ("didox_statement", "Didox Ma'lumotnoma"),
                    ("other", "Boshqa hujjat"),
                ],
                max_length=50,
                verbose_name="Hujjat turi",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="contract_document",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"document_type": "contract"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contract_orders",
                to="api.document",
                verbose_name="Shartnoma hujjati",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="invoice_document",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"document_type": "invoice"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invoice_orders",
                to="api.document",
                verbose_name="Hisob-faktura hujjati",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_proof_document",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"document_type": "payment_proof"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payment_proof_orders",
                to="api.document",
                verbose_name="To'lov hujjati",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="ttn_document",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"document_type": "ttn"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ttn_orders",
                to="api.document",
                verbose_name="TTN hujjati",
            ),
        ),
    ]
