# Generated by Django 5.2.6 on 2025-10-01 08:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_alter_document_document_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="team_members",
            field=models.JSONField(
                blank=True, default=list, verbose_name="Jamoa a'zolari"
            ),
        ),
    ]
