# Generated by Django 5.2.6 on 2025-10-01 08:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_company_team_members"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyMember",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255, verbose_name="Ism")),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Egasi"),
                            ("admin", "Administrator"),
                            ("manager", "Menejer"),
                            ("employee", "Xodim"),
                            ("accountant", "Buxgalter"),
                        ],
                        default="employee",
                        max_length=20,
                        verbose_name="Rol",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Telefon raqami"
                    ),
                ),
                (
                    "telegram_username",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Telegram username"
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Faol")),
                (
                    "joined_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Qo'shilgan vaqt"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yangilangan vaqt"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="api.company",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Kompaniya a'zosi",
                "verbose_name_plural": "Kompaniya a'zolari",
                "db_table": "company_members",
                "unique_together": {("company", "user")},
            },
        ),
    ]
