# Generated by Django 5.2.6 on 2025-10-01 08:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0009_companymember"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_login_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Oxirgi kirish vaqti"
            ),
        ),
    ]
