# Generated by Django 5.2.6 on 2025-10-02 09:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0010_user_last_login_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="currency",
            field=models.CharField(default="UZS", max_length=3, verbose_name="Valyuta"),
        ),
    ]
