# Generated by Django 5.2.6 on 2025-10-03 06:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0011_add_currency_to_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="factory",
            name="contact_info",
            field=models.TextField(blank=True, verbose_name="Aloqa ma'lumotlari"),
        ),
        migrations.AddField(
            model_name="factory",
            name="description",
            field=models.TextField(blank=True, verbose_name="Tavsif"),
        ),
        migrations.AddField(
            model_name="factory",
            name="website",
            field=models.URLField(blank=True, verbose_name="Veb-sayt"),
        ),
    ]
